name: multiple_result_async
description: Provide methods to handle Result mapping and chaining with asynchronous operations.
version: 0.0.2
repository: https://github.com/DIG-/dart-multiple-result-async
topics:
  - result
  - utility

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  multiple_result: ^5.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
